name: wonk_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  auto_route: ^9.2.2
  either_dart: ^1.0.0
  flutter_dotenv: ^5.1.0
  flutter_map: ^7.0.2
  flutter_solidart: ^1.7.1
  get_it: ^8.0.0
  google_sign_in: ^6.2.1
  injectable: ^2.5.0
  latlong2: ^0.9.1
  phosphor_flutter: ^2.1.0
  rive: ^0.13.14
  shadcn_ui: ^0.13.0
  solidart: ^1.5.4
  supabase_flutter: ^2.8.0
  geolocator: ^13.0.1
  flutter_map_marker_cluster: ^1.4.0
  cached_network_image: ^3.4.1
  text_marquee: ^0.0.2
  collection:
  animate_do: ^3.3.4

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/rive/
    - .env
